name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
          
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
        
      - name: Build Windows binary
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          fyne-cross windows -arch amd64 -output FiftySoundApp_windows_amd64 --app-id com.fiftysound
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            fyne-cross/bin/windows-amd64/FiftySoundApp_windows_amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
